function [] = plot_mcmc_posteriors()
    %%% command:
    %%% plot_mcmc_posteriors()

    clc;
    close all
   
    set(0,'DefaultFigureVisible','on');
   
    chains = [];
    for ii = 1:5
        iichains = load(strcat('./chains/chains_',num2str(ii),'.mat'));
        iichains = iichains.chains(:,:);
        for kk = 1:size(iichains,1)
            chains = [chains;iichains(kk,:)];
        end
    end

    chains(:,end) = round(10.^chains(:,end));
    
    a{1} = 'Log_{10} \beta';
    a{2} = 'Log_{10} \tau_L';
    a{3} = 'Log_{10} \tau_I';
    a{4} = 'Log_{10} p_{pfu}';
    a{5} = 'Log_{10} p_{rna}';
    a{6} = 'Log_{10} c_{pfu}';
    a{7} = 'Log_{10} \omega_0';
    a{8} = 'Log_{10} V_{pfu}^{stock}';
    a{9} = 'Log_{10} V_{rna}^{stock}';
    a{10} = 'n_L';
    figlabs = {a{1},...
                a{2},...
                a{3},...
                a{4},...
                a{5},...
                a{6},...
                a{7},...
                a{8},...
                a{9},...
                a{10}};
    
    fontsize = 14;

    XLim = {[-5.2 -4.5],...
            [0.9 1.05],...
            [1 1.7],...
            [5.1 5.8],...
            [5.85 6.45],...
            [-1.3 -1.1],...
            [0.65 0.73],...
            [4.8 5.1],...
            [5.07 5.21],...
            [12 30]};
    XTicks = {[-5.2,-4.85,-4.5],...
            [0.9,0.95,1.0,1.05],...
            [1,1.35,1.7],...
            [5.1,5.45,5.8],...
            [5.85,6.15,6.45],...
            [-1.3,-1.2,-1.1],...
            [0.65,0.69,0.73],...
            [4.8,4.9,5.0,5.1],...
            [5.07,5.14,5.21],...
            [12,18,24,30]};
             
    tiledplot = tiledlayout(2,5,'TileSpacing','Compact');
    set(gcf, 'Position',  [300, 100, 1300, 450]);
    for aa = 1:length(figlabs)
        ax(aa) = nexttile(aa);

        if ~ismember(aa,[1,6])
            set(ax(aa),...
              'box','on',...
              'XLim', XLim{aa},...
              'XTick', XTicks{aa},...
              'YLim', [0 0.2],...
              'YTickLabels', [],...
              'FontSize',fontsize); 
        else
            set(ax(aa),...
              'box','on',...
              'XLim', XLim{aa},...
              'XTick', XTicks{aa},...
              'YLim', [0 0.2],...
              'FontSize',fontsize); 
        end
        set(gca,'TickLength',[0.02, 0.01])
        hold on;
        histogram(chains(:,aa), Normalization="probability",...
                                DisplayStyle="bar",...
                                FaceColor=[0 0 0],...
                                FaceAlpha=0.35,...
                                EdgeColor=[0 0 0],...
                                EdgeAlpha=1); 
        text(0.075,0.85,figlabs{aa},...
        'Units','Normalized',...
        'HorizontalAlignment','left',...
        'FontSize',fontsize,...
        'FontWeight','Normal');
    end
    ylabel(tiledplot,'Normalized frequency', fontsize=fontsize);
    tiledplot.TileSpacing = 'compact';
    tiledplot.Padding = 'compact'; 


    %%% save figure %%%
    if ~exist('./figures', 'dir')
        mkdir('./figures')
    end
    exportgraphics(gcf,'figures/corner_carrib.png','Resolution',600);
    % exportgraphics(gcf,'../../LaTeX/figures/corner_carrib.eps','ContentType','vector');

    end