function []=plot_mcmc_posteriors()

    close all;
    clc;
    clear all;

    
    a{1} = 'Log_{10} \beta';
    a{2} = 'Log_{10} \tau_L';
    a{3} = 'Log_{10} \tau_I';
    a{4} = 'Log_{10} p_{pfu}';
    a{5} = 'Log_{10} p_{rna}';
    a{6} = 'Log_{10} \tau_V';
    a{7} = 'Log_{10} c_{rna}';
    a{8} = 'Log_{10} \omega_0';
    a{9} = 'Log_{10} V_{pfu}^{stock}';
    a{10} = 'Log_{10} V_{rna}^{stock}';
    a{11} = 'Log_{10} V_{0,rna}';
    a{12} = 'n_L';
    a{13} = 'n_V';
    figlabs = {a{1},...
            a{2},...
            a{3},...
            a{4},...
            a{5},...
            a{6},...
            a{7},...
            a{8},...
            a{9},...
            a{10},...
            a{11},...
            a{12},...
            a{13}};

    fontsize = 12;

    XLim = {[-5 1],...
            [0.95 1.11],...
            [1.1 1.3],...
            [4.4 4.8],...
            [6.8 7.1],...
            [1.45 1.55],...
            [-3.4 -2.0],...
            [0.61 0.67],...
            [4.8 5.1],...
            [6.9 7.3],...
            [7.3 7.7],...
            [10 30],...
            [12 24]};
    XTicks = {[-5,-3,-1,1],...
            [0.95,1.03,1.11],...
            [1.1,1.2,1.3],...
            [4.4,4.6,4.8],...
            [6.8,6.95,7.1],...
            [1.45,1.5,1.55],...
            [-3.4,-2.7,-2.0],...
            [0.61,0.64,0.67],...
            [4.8,4.95,5.1],...
            [6.9,7.1,7.3],...
            [7.3,7.5,7.7],...
            [10,20,30],...
            [12,18,24]};

    chains = [];
    for nn = 1:5
        kkchains = load(strcat('./chains/chains_',num2str(nn),'.mat'));
        chains = [chains; kkchains.chains(:,:);];
    end
    chains(:,end-1) = round(10.^chains(:,end-1));
    chains(:,end)   = round(10.^chains(:,end));


    tiledplot = tiledlayout(3,5,'TileSpacing','Compact');
    set(gcf, 'Position',  [300, 100, 1250, 525]);
    for aa = 1:length(figlabs)
        ax(aa) = nexttile(aa);

        if ~ismember(aa,[1,6,11])
            set(ax(aa),...
              'box','on',...
              'XLim', XLim{aa},...
              'XTick', XTicks{aa},...
              'YLim', [0 0.25],...
              'YTickLabels', [],...
              'FontSize',fontsize);

        else
            set(ax(aa),...
              'box','on',...
              'XLim', XLim{aa},...
              'XTick', XTicks{aa},...
              'YLim', [0 0.25],...
              'FontSize',fontsize); 
        end
        set(gca,'TickLength',[0.02, 0.01])
        hold on;
        histogram(chains(:,aa), Normalization="probability",...
                                DisplayStyle="bar",...
                                FaceColor=[0 0 0],...
                                FaceAlpha=0.35,...
                                EdgeColor=[0 0 0],...
                                EdgeAlpha=1);        

        if ismember(aa,[1])
            text(0.55,0.85,figlabs{aa},...
            'Units','Normalized',...
            'HorizontalAlignment','left',...
            'FontSize',fontsize,...
            'FontWeight','Normal');
        else
            text(0.075,0.85,figlabs{aa},...
            'Units','Normalized',...
            'HorizontalAlignment','left',...
            'FontSize',fontsize,...
            'FontWeight','Normal');
        end
    end
    ylabel(tiledplot,'Normalized frequency', fontsize=fontsize);
    tiledplot.TileSpacing = 'compact';
    tiledplot.Padding = 'compact'; 

    %%% save figure %%%
    if ~exist('./figures', 'dir')
        mkdir('./figures')
    end
    exportgraphics(gcf,'./figures/corner_iol.png','Resolution',600);
    % exportgraphics(gcf,'../../LaTeX/figures/corner_iol.eps','ContentType','vector');

end